### ISSUE TITLE
Crash on Startup in latest build.

### ISSUE THREAD

**Issue by NotAPotter** [ArshiaDPG/Nears-Fabric#2]
Log:
[latest.log](https://github.com/user-attachments/files/17237534/latest.log)

**Comment by Poopooracoocoo** [comment]
The issue is that it's compiled for Java 21. 1.20.1 mods should not be compiled for Java 21 as it uses Java 17.

**Comment by MinecraftGuy926** [comment]
bump

**Comment by MinecraftGuy926** [comment]
https://modrinth.com/mod/nears/version/POkHQ3qP fixed
